In [1]:
#1. Dataset
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [2]:
print("Banyak data: ",len(x))

Banyak data:  150


In [3]:
print('15 data pertama: ')
print(x[:15])

15 data pertama: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]]


In [4]:
#2. Split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size = 0.7)

In [5]:
print('Banyak data latih: ', len(x_train))
print('Banyak data latih: ', len(x_test))

Banyak data latih:  105
Banyak data latih:  45


In [6]:
#K-Fold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

model = SVC(kernel='linear', C=1)
scores = cross_val_score(model,x,y,cv=5)
print("Akurasi svm setiap fold: ",scores)
print("Akurasi svm demgam lima fold: ",scores.mean)

Akurasi svm setiap fold:  [0.96666667 1.         0.96666667 0.96666667 1.        ]
Akurasi svm demgam lima fold:  <built-in method mean of numpy.ndarray object at 0x00000196DF92FBD0>


In [7]:
#ujicoba model klasifikasi
#1. KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

knn = KNeighborsClassifier()

knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
score = metrics.accuracy_score(y_test,y_pred)
print('Akurasi: ',score)

Akurasi:  0.9777777777777777


In [8]:
#DTree
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

dt = DecisionTreeClassifier(max_depth = None, min_samples_split= 2)
dt.fit(x_train, y_train)

y_pred = dt.predict(x_test)
score = metrics.accuracy_score(y_test,y_pred)
print('Akurasi: ',score)

Akurasi:  0.9555555555555556


In [9]:
#SVM
from sklearn.svm import SVC
from sklearn import metrics

svm = SVC(kernel='rbf', C = 1, gamma = 0.01)
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)
score = metrics.accuracy_score(y_test,y_pred)
print('Akurasi: ',score)

Akurasi:  0.8888888888888888


In [10]:
svmLinear = SVC(kernel='linear', C = 1)
svmLinear.fit(x_train, y_train)
y_pred = svmLinear.predict(x_test)
score = metrics.accuracy_score(y_test,y_pred)
print('Akurasi: ',score)

Akurasi:  0.9777777777777777


In [11]:
#4.  Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
score = metrics.accuracy_score(y_test,y_pred)
print('Akurasi: ',score)

Akurasi:  0.9555555555555556


In [12]:
#5. Naive Bayes
from sklearn.naive_bayes import BernoulliNB
from sklearn import metrics

nb = BernoulliNB()
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)
score = metrics.accuracy_score(y_test,y_pred)
print('Akurasi: ',score)

Akurasi:  0.24444444444444444
